events {}

http {

    upstream terrain_app {
        server web1:8080;
        server web2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://terrain_app;
        }
    }
}