spring.application.name=terrain-rental

spring.datasource.url=jdbc:mysql://localhost:3307/rin_nairith-db
spring.datasource.username=root
spring.datasource.password=Hello@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

application.title=Terrain Rental System
application.version=1.0.0
spring.main.banner-mode=console
# spring.main.banner-mode=off

debug=false